// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVutKbV4YStIkciaeUCPzOV8Gx039x8Jk',
    appId: '1:789403567826:web:b92204e9150d3b0e468f0b',
    messagingSenderId: '789403567826',
    projectId: 'todo-app-c11-34855',
    authDomain: 'todo-app-c11-34855.firebaseapp.com',
    storageBucket: 'todo-app-c11-34855.appspot.com',
    measurementId: 'G-XH3JPBY7HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC92SbJu3MrffhSuRYPDGGuZ9uJy5GMCt8',
    appId: '1:789403567826:android:1745ca821c340f20468f0b',
    messagingSenderId: '789403567826',
    projectId: 'todo-app-c11-34855',
    storageBucket: 'todo-app-c11-34855.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVutKbV4YStIkciaeUCPzOV8Gx039x8Jk',
    appId: '1:789403567826:web:8ab9293d418ef369468f0b',
    messagingSenderId: '789403567826',
    projectId: 'todo-app-c11-34855',
    authDomain: 'todo-app-c11-34855.firebaseapp.com',
    storageBucket: 'todo-app-c11-34855.appspot.com',
    measurementId: 'G-THSF3Q61MM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN0Evw-kgzG3jGwRpdjQRKbn-OsCRwyxE',
    appId: '1:789403567826:ios:dfe98ed95d725454468f0b',
    messagingSenderId: '789403567826',
    projectId: 'todo-app-c11-34855',
    storageBucket: 'todo-app-c11-34855.appspot.com',
    iosBundleId: 'com.example.todoC11',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN0Evw-kgzG3jGwRpdjQRKbn-OsCRwyxE',
    appId: '1:789403567826:ios:dfe98ed95d725454468f0b',
    messagingSenderId: '789403567826',
    projectId: 'todo-app-c11-34855',
    storageBucket: 'todo-app-c11-34855.appspot.com',
    iosBundleId: 'com.example.todoC11',
  );

}